"""
MediVerse AI — Provider Abstraction Interface
=============================================
Defines the canonical interface for every AI module.

All service files call these functions.
To swap AI provider → local model: change the implementation in providers/,
NOT the callers in services/.

Architecture:
  services/symptom_service.py → ai.providers.symptom_checker.check_symptoms()
  services/xray_service.py    → ai.providers.xray.analyze_xray()
  ...etc

Each provider function returns a standard ProviderResult.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ProviderResult:
    """
    Canonical result from any AI provider.
    Downstream services map this to their own response schemas.
    """
    # Core prediction
    primary_label: str          # e.g. "High Risk" / "Pneumonia" / "Melanoma"
    confidence: float           # 0.0–100.0
    risk_tier: str = "unknown"  # low | moderate | high | critical | unknown

    # Supporting data
    conditions: list[dict] = field(default_factory=list)   # [{name, probability}]
    factors: list[dict] = field(default_factory=list)       # risk factors / features
    suggestions: list[str] = field(default_factory=list)

    # Metadata
    provider: str = "ai"    # ai | local | rule_engine | hybrid
    model_version: str = "nim-or-secondary"
    is_temporary: bool = True   # Always True until custom model deployed
    ai_provider_label: str = "AI Model (Temporary)"

    # Cost / perf tracking
    latency_ms: float = 0.0
    prompt_tokens: int = 0
    output_tokens: int = 0

    # Raw AI text (for debugging)
    raw_response: str = ""

    # Disclaimer appended to all outputs
    disclaimer: str = ""
    ai_badge: str = "🤖 Powered by AI (Beta — Temporary)"


MEDICAL_DISCLAIMER = (
    "⚠️ IMPORTANT: This result was generated by a temporary AI system "
    "(NVIDIA NIM or secondary AI) and is NOT a validated clinical decision-support tool. "
    "It is provided for informational and screening purposes ONLY. "
    "Do NOT use this as a substitute for professional medical advice, "
    "diagnosis, or treatment. Always consult a qualified healthcare provider."
)
