"""
MediVerse AI — ECG Provider (Signal Analysis + Gemini Support)
==============================================================
Strategy:
  1. Run deterministic signal analysis (R-peak detection, HR, quality)
     using scipy — lightweight, no model needed.
  2. Extract waveform features (heart rate, rhythm regularity, QRS duration hint)
  3. Send feature text to Gemini for rhythm interpretation and clinical guidance.

Swap path: Replace _call_gemini_ecg() with your ONNX ResNet1D/CNN-LSTM model.

Note: Image-mode ECG (photo of paper ECG) → Gemini Vision.
      Signal-mode ECG (.csv/.npy) → Signal analysis + Gemini text.
"""
from __future__ import annotations

import logging
from typing import Optional

import numpy as np

from app.ai.gemini_client import get_client
from app.ai.provider_types import ProviderResult, MEDICAL_DISCLAIMER

logger = logging.getLogger("mediverse.ai.ecg")

ECG_DISCLAIMER = (
    "⚠️ CARDIAC SAFETY NOTICE: This ECG analysis is generated by a TEMPORARY AI system "
    "and is NOT a validated cardiac diagnostic tool. "
    "If you are experiencing chest pain, shortness of breath, jaw/arm pain, "
    "or palpitations — call emergency services (112/911) IMMEDIATELY. "
    "Always consult a qualified cardiologist for ECG interpretation. "
    + MEDICAL_DISCLAIMER
)

# PTB-XL compatible rhythm classes
RHYTHM_CLASSES = [
    "Normal Sinus Rhythm", "Sinus Bradycardia", "Sinus Tachycardia",
    "Atrial Fibrillation", "Atrial Flutter", "Supraventricular Tachycardia",
    "Ventricular Tachycardia", "Left Bundle Branch Block", "Right Bundle Branch Block",
    "First Degree AV Block", "ST Elevation", "ST Depression",
    "Left Ventricular Hypertrophy", "Premature Atrial Contractions",
    "Premature Ventricular Contractions",
]

_SCHEMA = """{
  "rhythm_type": "<rhythm classification>",
  "confidence": <0-100>,
  "severity": "<normal|mild|moderate|severe|critical>",
  "all_probabilities": [
    {"label": "<rhythm>", "probability": <0-100>}
  ],
  "recommendation": "<clinical action recommendation>",
  "risk_flags": ["<specific concern>"],
  "needs_review": <true|false>,
  "clinical_interpretation": "<structured ECG interpretation>"
}"""


def _detect_r_peaks(signal: np.ndarray, fs: float = 500.0) -> list[int]:
    """
    Simple R-peak detection using scipy find_peaks.
    Fallback to empty list on failure.
    """
    try:
        from scipy.signal import find_peaks, butter, filtfilt

        # Bandpass filter 0.5–40 Hz
        b, a = butter(3, [0.5 / (fs / 2), 40.0 / (fs / 2)], btype="band")
        filtered = filtfilt(b, a, signal)

        # Find peaks above 60% of max amplitude
        height = 0.6 * np.max(np.abs(filtered))
        min_dist = int(0.3 * fs)  # min 300ms between beats
        peaks, _ = find_peaks(filtered, height=height, distance=min_dist)
        return peaks.tolist()
    except Exception as exc:
        logger.warning("R-peak detection failed: %s", exc)
        return []


def _signal_features(signal: np.ndarray, fs: float = 500.0) -> dict:
    """
    Extract numeric features from raw ECG signal.
    No ML required — pure signal processing.
    """
    duration_s = len(signal) / fs
    r_peaks = _detect_r_peaks(signal, fs)

    # Heart rate
    hr_bpm: float | None = None
    rr_intervals: list[float] = []
    if len(r_peaks) >= 2:
        rr_samples = np.diff(r_peaks)
        rr_intervals = (rr_samples / fs).tolist()
        hr_bpm = round(60.0 / np.mean(rr_intervals), 1)

    # Rhythm regularity (coefficient of variation of RR intervals)
    rr_cv = round(float(np.std(rr_intervals) / (np.mean(rr_intervals) + 1e-6)), 3) if rr_intervals else 0.0

    # Signal quality
    amplitude = float(np.max(signal) - np.min(signal))
    noise_est = float(np.std(np.diff(signal)))
    snr = round(amplitude / (noise_est + 1e-6), 2)

    quality = "good"
    quality_warnings = []
    if len(r_peaks) < 3:
        quality = "poor"
        quality_warnings.append("Too few R-peaks detected — signal may be noisy or too short.")
    elif snr < 5:
        quality = "noisy"
        quality_warnings.append("High signal noise detected — quality may affect accuracy.")
    elif duration_s < 5:
        quality = "short"
        quality_warnings.append("Recording shorter than 5 seconds — longer recordings are more reliable.")

    return {
        "duration_s":       round(duration_s, 1),
        "n_samples":        len(signal),
        "sample_rate_hz":   fs,
        "r_peak_count":     len(r_peaks),
        "r_peaks":          r_peaks[:50],  # limit for schema
        "heart_rate_bpm":   hr_bpm,
        "rr_cv":            rr_cv,  # >0.15 suggests AF
        "amplitude":        round(amplitude, 4),
        "snr":              snr,
        "signal_quality":   quality,
        "quality_warnings": quality_warnings,
    }


async def analyze_ecg_signal(signal: np.ndarray, fs: float = 500.0) -> ProviderResult:
    """
    Analyse 1D ECG signal.
    Step 1: signal features via scipy
    Step 2: Gemini rhythm interpretation
    """
    feats = _signal_features(signal, fs)

    # Preliminary heuristic flags
    hr = feats.get("heart_rate_bpm")
    rr_cv = feats["rr_cv"]
    prelim_notes = []
    if hr:
        if hr < 60:
            prelim_notes.append(f"Bradycardia: HR={hr} bpm (< 60)")
        elif hr > 100:
            prelim_notes.append(f"Tachycardia: HR={hr} bpm (> 100)")
        else:
            prelim_notes.append(f"Heart rate in normal range: HR={hr} bpm")
    if rr_cv > 0.2:
        prelim_notes.append(f"Irregular RR intervals (CV={rr_cv:.2f}) — possible AF or ectopic beats")

    prompt = f"""You are an AI cardiac rhythm analysis assistant supporting a clinical ECG screening tool.

Signal analysis results (computed from the uploaded waveform):
- Duration: {feats['duration_s']} seconds
- Sample rate: {feats['sample_rate_hz']} Hz
- Detected R-peaks: {feats['r_peak_count']}
- Estimated Heart Rate: {feats.get('heart_rate_bpm', 'N/A')} bpm
- RR Interval Variability (CV): {feats['rr_cv']} (>0.15 may suggest AF/irregular rhythm)
- Signal Quality: {feats['signal_quality']}
- Preliminary observations: {'; '.join(prelim_notes) or 'None'}

Task: Provide a comprehensive ECG rhythm interpretation.
- Classify the rhythm from: {', '.join(RHYTHM_CLASSES)}
- Assign severity: normal < mild < moderate < severe < critical
- Provide top 3 rhythm possibilities with confidence percentages
- Flag any risk features (ST changes, extreme HR, irregular rhythm)
- Recommend appropriate clinical action
- Indicate if cardiologist review is needed

Be clinically grounded. This is a SCREENING tool — not diagnostic.
Flag needs_review=true for any non-sinus or high-risk rhythm."""

    try:
        client = get_client()
        resp = await client.generate_json(prompt, schema_hint=_SCHEMA)

        if resp.data:
            d = resp.data
            rhythm = d.get("rhythm_type", "Indeterminate")
            conf = float(d.get("confidence", 65.0))
            all_probs = d.get("all_probabilities", [
                {"label": rhythm, "probability": conf},
            ])
            risk_flags = list(d.get("risk_flags", []))
            rec = d.get("recommendation", "Consult a cardiologist for ECG interpretation.")
            clin_note = d.get("clinical_interpretation", "")

            suggestions = [rec]
            if clin_note:
                suggestions.insert(0, f"📋 {clin_note}")
            if prelim_notes:
                suggestions.extend([f"📊 {n}" for n in prelim_notes])

            return ProviderResult(
                primary_label=rhythm,
                confidence=conf,
                risk_tier=_severity_to_tier(d.get("severity", "mild")),
                conditions=all_probs,
                factors=[
                    {"factor": "Heart Rate",     "value": f"{hr or 'N/A'} bpm",    "impact": _hr_impact(hr)},
                    {"factor": "RR Variability", "value": str(feats["rr_cv"]),     "impact": "high" if rr_cv > 0.2 else "low"},
                    {"factor": "Signal Quality", "value": feats["signal_quality"], "impact": "moderate"},
                ],
                suggestions=suggestions,
                provider="gemini+signal",
                model_version="gemini-ecg-temp-v1",
                is_temporary=True,
                latency_ms=resp.latency_ms,
                prompt_tokens=resp.prompt_tokens,
                output_tokens=resp.output_tokens,
                raw_response=resp.text,
                disclaimer=ECG_DISCLAIMER,
                ai_provider_label="Gemini AI + Signal Analysis (Temporary)",
            ), feats

    except Exception as exc:
        logger.warning("Gemini ECG analysis failed: %s", exc)

    # Fallback: signal features only, no ML
    fallback_rhythm = "Indeterminate"
    if hr and hr < 60:
        fallback_rhythm = "Possible Sinus Bradycardia"
    elif hr and hr > 100:
        fallback_rhythm = "Possible Sinus Tachycardia"
    elif rr_cv > 0.2:
        fallback_rhythm = "Irregular Rhythm (possible AF)"
    elif hr and 60 <= hr <= 100 and rr_cv < 0.15:
        fallback_rhythm = "Normal Sinus Rhythm (estimated)"

    return ProviderResult(
        primary_label=fallback_rhythm,
        confidence=50.0,
        risk_tier="moderate",
        conditions=[{"label": fallback_rhythm, "probability": 50.0}],
        factors=[{"factor": "Heart Rate", "value": f"{hr or 'N/A'} bpm", "impact": _hr_impact(hr)}],
        suggestions=[
            "AI interpretation service unavailable — signal features only.",
            f"Estimated rhythm: {fallback_rhythm}",
            "Please consult a cardiologist for definitive ECG interpretation.",
        ],
        provider="signal_only",
        model_version="signal-heuristic-v1",
        is_temporary=True,
        disclaimer=ECG_DISCLAIMER,
    ), feats


def _severity_to_tier(sev: str) -> str:
    return {"normal": "low", "mild": "low", "moderate": "moderate", "severe": "high", "critical": "high"}.get(sev, "moderate")


def _hr_impact(hr: float | None) -> str:
    if hr is None:
        return "unknown"
    if hr < 50 or hr > 130:
        return "high"
    elif hr < 60 or hr > 100:
        return "moderate"
    return "low"
