"""
MediVerse AI — Chest X-Ray Provider (Gemini Vision)
====================================================
Uses Gemini multimodal to analyse chest X-ray images.

Covers 17 CheXpert/NIH-14 categories for schema compatibility.
Strict clinical disclaimer always included.

Swap path: Replace with ONNX EfficientNet-B4 ensemble when trained.
"""
from __future__ import annotations

import logging

from app.ai.gemini_client import get_client
from app.ai.provider_types import ProviderResult, MEDICAL_DISCLAIMER

logger = logging.getLogger("mediverse.ai.xray")

# Compatible with existing xray_service.py schema (17 conditions)
XRAY_CONDITIONS = [
    "No Finding", "Atelectasis", "Cardiomegaly", "Consolidation",
    "Edema", "Effusion", "Emphysema", "Fibrosis", "Hernia",
    "Infiltration", "Mass", "Nodule", "Pleural Thickening",
    "Pneumonia", "Pneumothorax", "Pleural Effusion", "Fracture",
]

HIGH_RISK_CONDITIONS = {
    "Pneumothorax", "Pneumonia", "Cardiomegaly", "Effusion",
    "Consolidation", "Edema", "Mass", "Nodule",
}

_SCHEMA = """{
  "top_condition": "<condition name>",
  "top_label": "<same as top_condition>",
  "confidence": <0-100>,
  "top3": [
    {"code": "<snake_case>", "label": "<condition>", "confidence": <0-100>}
  ],
  "all_probabilities": {
    "<condition_name>": <0-100>
  },
  "severity": "<normal|mild|moderate|severe|critical>",
  "is_high_risk": <true|false>,
  "care_suggestions": ["<suggestion>"],
  "radiological_notes": "<brief structured radiology assessment>",
  "image_quality": "<good|acceptable|poor>",
  "quality_warnings": ["<warning>"]
}"""

_PROMPT = f"""You are an AI radiology assistant supporting a clinical chest X-ray screening tool.
Analyse this chest X-ray image and provide a structured preliminary assessment.

⚠️ IMPORTANT CONTEXT:
- This is a SCREENING TOOL ONLY — not a diagnostic system
- All findings must be verified by a qualified radiologist
- Err on the side of caution — flag potential abnormalities

Assess the chest X-ray for these 17 conditions:
{', '.join(XRAY_CONDITIONS)}

Instructions:
1. Identify the most likely primary finding (including "No Finding" if normal)
2. List top 3 possible findings with confidence %
3. Estimate probability for ALL 17 conditions (0-100)
4. Assess severity: normal < mild < moderate < severe < critical
5. Flag is_high_risk=true for any of: Pneumothorax, Pneumonia, Cardiomegaly, Effusion, Mass, Nodule, Consolidation, Edema
6. Comment on image quality (rotation, exposure, cut-off anatomy)
7. Provide 3-4 care/follow-up recommendations

Respond ONLY in valid JSON format.
Be conservative — if uncertain, include a disclaimer in radiological_notes."""


async def analyze_xray(image_bytes: bytes, filename: str = "") -> ProviderResult:
    """
    Analyse chest X-ray image using Gemini Vision.
    Returns ProviderResult compatible with XrayAnalysisResponse schema.
    """
    mime_type = _detect_mime(image_bytes)
    # X-rays are often DICOM-converted to JPEG or PNG
    if mime_type not in ("image/jpeg", "image/png", "image/webp"):
        mime_type = "image/jpeg"

    xray_disclaimer = (
        "⚠️ This AI X-ray analysis is generated by a TEMPORARY Gemini Vision system. "
        "It is NOT a validated radiology tool. All findings require review by a "
        "qualified radiologist or physician before any clinical action is taken. "
        + MEDICAL_DISCLAIMER
    )

    try:
        client = get_client()
        resp = await client.analyze_image_json(
            image_bytes,
            _PROMPT,
            mime_type=mime_type,
            schema_hint=_SCHEMA,
        )

        if resp.data:
            d = resp.data
            top = d.get("top_condition", "No Finding")
            conf = float(d.get("confidence", 60.0))
            all_probs = d.get("all_probabilities", {})

            # Ensure all 17 conditions present
            for cond in XRAY_CONDITIONS:
                all_probs.setdefault(cond, 0.0)

            conditions = [
                {"name": k, "probability": float(v)}
                for k, v in sorted(all_probs.items(), key=lambda x: x[1], reverse=True)
            ]

            care = d.get("care_suggestions", [])
            rad_note = d.get("radiological_notes", "")
            if rad_note:
                care.insert(0, f"📋 {rad_note}")

            return ProviderResult(
                primary_label=top,
                confidence=conf,
                risk_tier=_severity_to_tier(d.get("severity", "mild")),
                conditions=conditions,
                factors=[
                    {"factor": "Top Finding",   "value": top,                                "impact": d.get("severity", "unknown")},
                    {"factor": "Is High Risk",  "value": str(d.get("is_high_risk", False)),  "impact": "high"},
                    {"factor": "Image Quality", "value": d.get("image_quality", "unknown"),  "impact": "low"},
                ],
                suggestions=care,
                provider="gemini_vision",
                model_version="gemini-vision-xray-temp-v1",
                is_temporary=True,
                latency_ms=resp.latency_ms,
                prompt_tokens=resp.prompt_tokens,
                output_tokens=resp.output_tokens,
                raw_response=resp.text,
                disclaimer=xray_disclaimer,
                ai_provider_label="Gemini Vision AI (Temporary — X-Ray Beta)",
            )

    except Exception as exc:
        logger.warning("Gemini X-ray analysis failed: %s", exc)

    return ProviderResult(
        primary_label="Analysis Unavailable",
        confidence=0.0,
        risk_tier="unknown",
        conditions=[],
        suggestions=[
            "X-ray AI service is temporarily unavailable.",
            "Please consult a radiologist or physician for X-ray interpretation.",
        ],
        provider="fallback",
        model_version="fallback-v1",
        is_temporary=True,
        disclaimer=xray_disclaimer,
    )


def _severity_to_tier(severity: str) -> str:
    return {
        "normal":   "low",
        "mild":     "low",
        "moderate": "moderate",
        "severe":   "high",
        "critical": "high",
    }.get(severity, "moderate")


def _detect_mime(data: bytes) -> str:
    """Detect image MIME type from magic bytes (imghdr removed in Python 3.13)."""
    if data[:3] == b'\xff\xd8\xff':
        return "image/jpeg"
    if data[:8] == b'\x89PNG\r\n\x1a\n':
        return "image/png"
    if data[:4] == b'RIFF' and data[8:12] == b'WEBP':
        return "image/webp"
    return "image/jpeg"
