"use client";

import React from "react";

interface AIProviderBadgeProps {
  /** e.g. "AI Inference (Temporary)" */
  providerLabel?: string;
  /** Show/hide the badge */
  show?: boolean;
  /** Additional CSS classes */
  className?: string;
}

/**
 * AIProviderBadge
 * ---------------
 * Shown on any module result that is powered by a temporary AI provider
 * (NVIDIA NIM / Fallback) instead of a custom-trained model.
 *
 * When custom models are deployed, set show=false or remove the badge.
 */
export function AIProviderBadge({
  providerLabel = "AI Inference (Temporary)",
  show = true,
  className = "",
}: AIProviderBadgeProps) {
  if (!show) return null;

  return (
    <div
      className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium
        bg-amber-500/10 border border-amber-500/30 text-amber-400
        backdrop-blur-sm ${className}`}
    >
      <span className="relative flex h-2 w-2">
        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75" />
        <span className="relative inline-flex rounded-full h-2 w-2 bg-amber-500" />
      </span>
      <span>🤖 {providerLabel}</span>
    </div>
  );
}

/**
 * AITemporaryDisclaimer
 * ---------------------
 * Full disclaimer block to be shown below any AI-generated medical result.
 */
export function AITemporaryDisclaimer({
  children,
  className = "",
}: {
  children?: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={`rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 space-y-2 ${className}`}
    >
      <div className="flex items-start gap-2">
        <span className="text-amber-400 text-base mt-0.5">⚠️</span>
        <div className="space-y-1">
          <p className="text-xs font-semibold text-amber-400">
            Temporary AI System Notice
          </p>
          <p className="text-xs text-zinc-400 leading-relaxed">
            This result was generated by a temporary AI system
            as a bridge solution. It is{" "}
            <strong className="text-zinc-300">
              NOT a validated clinical decision-support tool
            </strong>{" "}
            and is provided for informational and screening purposes only. Do
            NOT use as a substitute for professional medical advice, diagnosis,
            or treatment.{" "}
            <strong className="text-zinc-300">
              Always consult a qualified healthcare provider.
            </strong>
          </p>
          {children && (
            <div className="text-xs text-zinc-500">{children}</div>
          )}
        </div>
      </div>
    </div>
  );
}

/**
 * AIConfidenceBar
 * ---------------
 * Visual confidence indicator for AI results.
 */
export function AIConfidenceBar({
  confidence,
  label = "AI Confidence",
}: {
  confidence: number;
  label?: string;
}) {
  const pct = Math.min(100, Math.max(0, confidence));
  const color =
    pct >= 75 ? "bg-emerald-500" : pct >= 50 ? "bg-amber-500" : "bg-red-500";
  const textColor =
    pct >= 75
      ? "text-emerald-400"
      : pct >= 50
      ? "text-amber-400"
      : "text-red-400";

  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <span className="text-xs text-zinc-400">{label}</span>
        <span className={`text-xs font-semibold ${textColor}`}>
          {pct.toFixed(0)}%
        </span>
      </div>
      <div className="h-1.5 rounded-full bg-zinc-800 overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-700 ${color}`}
          style={{ width: `${pct}%` }}
        />
      </div>
      {pct < 65 && (
        <p className="text-xs text-amber-400/80">
          ⚠️ Low confidence — results may be unreliable. Consult a specialist.
        </p>
      )}
    </div>
  );
}
