"""
PDF Report Generator for MediVerse AI
======================================
Uses weasyprint (CSS-based) with an HTML template.
Falls back to fpdf2 if weasyprint is unavailable.

Install: pip install weasyprint  OR  pip install fpdf2
"""
from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Any

logger = logging.getLogger("mediverse.pdf_service")


# ── Module config ──────────────────────────────────────────────────────────────

MODULE_META = {
    "diabetes":     {"label": "Diabetes Risk Assessment", "color": "#8b5cf6", "icon": "🧪"},
    "xray":         {"label": "Chest X-Ray Analysis",     "color": "#3b82f6", "icon": "🫁"},
    "ecg":          {"label": "ECG Rhythm Analysis",      "color": "#ef4444", "icon": "❤️"},
    "skin":         {"label": "Skin Lesion Screening",    "color": "#f97316", "icon": "🔬"},
    "prescription": {"label": "Prescription OCR",         "color": "#10b981", "icon": "💊"},
    "symptoms":     {"label": "Symptom Checker",          "color": "#eab308", "icon": "🩺"},
}


# ── HTML Template ──────────────────────────────────────────────────────────────

def _build_html(report_data: dict, user_name: str, user_email: str) -> str:
    meta    = MODULE_META.get(report_data["module_type"], {"label": report_data["module_type"], "color": "#6366f1", "icon": "📋"})
    result  = report_data.get("result_json", {})
    created = datetime.fromisoformat(str(report_data.get("created_at", datetime.now().isoformat())))
    conf    = report_data.get("confidence")
    conf_pct = f"{conf * 100:.1f}%" if conf and conf <= 1.0 else (f"{conf:.1f}%" if conf else "N/A")

    def _row(label: str, value: Any) -> str:
        if value is None or value == "" or value == []:
            return ""
        if isinstance(value, list):
            value = ", ".join(str(v) for v in value)
        return f"""
        <tr>
          <td class="label">{label}</td>
          <td class="value">{value}</td>
        </tr>"""

    # Build result table rows dynamically from result_json
    result_rows = ""
    priority_keys = [
        ("rhythm_type",      "Rhythm / Diagnosis"),
        ("prediction",       "Prediction"),
        ("risk_level",       "Risk Level"),
        ("severity",         "Severity"),
        ("confidence",       "Confidence"),
        ("heart_rate_bpm",   "Heart Rate"),
        ("signal_quality",   "Signal Quality"),
        ("recommendation",   "Recommendation"),
        ("risk_flags",       "Risk Flags"),
        ("medications",      "Medications"),
        ("conditions",       "Conditions"),
        ("body_part",        "Body Part"),
        ("diseases",         "Detected Conditions"),
    ]
    shown = set()
    for key, label in priority_keys:
        val = result.get(key)
        if val is not None:
            result_rows += _row(label, val)
            shown.add(key)

    # Any remaining non-boring keys
    skip = {"disclaimer", "is_demo", "model_version", "report_id", "all_probabilities",
            "r_peaks", "grad_cam_base64", "heatmap_base64"}
    for key, val in result.items():
        if key not in shown and key not in skip and not key.endswith("_base64"):
            result_rows += _row(key.replace("_", " ").title(), val)

    # Risk flags
    risk_flags_html = ""
    flags = result.get("risk_flags", [])
    if flags:
        risk_flags_html = "<div class='flags'>" + "".join(
            f"<span class='flag'>{f}</span>" for f in flags
        ) + "</div>"

    # Disclaimer
    disclaimer = result.get("disclaimer") or (
        "This report is generated by MediVerse AI for screening purposes only. "
        "It is NOT a confirmed medical diagnosis. Always consult a qualified healthcare "
        "professional before making any medical decisions."
    )

    accent = meta["color"]

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Inter', Arial, sans-serif;
    color: #1a1a2e;
    background: #fff;
    font-size: 13px;
    line-height: 1.6;
  }}
  .header {{
    background: linear-gradient(135deg, #0f0f23 0%, #1a1a3e 100%);
    color: white;
    padding: 32px 40px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }}
  .brand {{ font-size: 22px; font-weight: 700; letter-spacing: -0.5px; }}
  .brand span {{ color: {accent}; }}
  .brand-sub {{ font-size: 11px; color: rgba(255,255,255,0.5); margin-top: 3px; }}
  .report-meta {{ text-align: right; font-size: 11px; color: rgba(255,255,255,0.6); }}
  .report-meta strong {{ color: white; display: block; font-size: 13px; margin-bottom: 4px; }}
  .module-banner {{
    background: {accent}15;
    border-left: 4px solid {accent};
    padding: 16px 40px;
    display: flex;
    align-items: center;
    gap: 12px;
  }}
  .module-icon {{ font-size: 24px; }}
  .module-title {{ font-size: 18px; font-weight: 700; color: {accent}; }}
  .module-sub {{ font-size: 11px; color: #64748b; margin-top: 2px; }}
  .section {{
    padding: 24px 40px;
    border-bottom: 1px solid #f1f5f9;
  }}
  .section-title {{
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #94a3b8;
    margin-bottom: 14px;
  }}
  .info-grid {{
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 16px;
  }}
  .info-card {{
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
    padding: 14px 16px;
  }}
  .info-card .lbl {{ font-size: 10px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }}
  .info-card .val {{ font-size: 16px; font-weight: 700; color: #1e293b; margin-top: 4px; }}
  .conf-bar-bg {{
    height: 6px; background: #e2e8f0; border-radius: 99px;
    margin-top: 6px; overflow: hidden;
  }}
  .conf-bar {{
    height: 100%; border-radius: 99px;
    background: {accent};
    width: {conf_pct if conf else '0%'};
  }}
  table.results {{
    width: 100%;
    border-collapse: collapse;
    font-size: 12.5px;
  }}
  table.results tr:nth-child(even) td {{ background: #f8fafc; }}
  table.results td {{ padding: 10px 12px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }}
  td.label {{ color: #64748b; font-weight: 500; width: 38%; white-space: nowrap; }}
  td.value {{ color: #1e293b; font-weight: 400; word-break: break-word; }}
  .flags {{ display: flex; flex-wrap: wrap; gap: 6px; margin-top: 8px; }}
  .flag {{
    background: #fef2f2; color: #dc2626;
    border: 1px solid #fecaca;
    border-radius: 6px; padding: 3px 10px;
    font-size: 11px; font-weight: 600;
  }}
  .disclaimer {{
    background: #fffbeb;
    border: 1px solid #fde68a;
    border-radius: 10px;
    padding: 14px 16px;
    font-size: 11px;
    color: #92400e;
    line-height: 1.7;
  }}
  .footer {{
    background: #f8fafc;
    padding: 20px 40px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 10px;
    color: #94a3b8;
    border-top: 1px solid #e2e8f0;
  }}
  .confidential {{
    background: #1a1a3e; color: white;
    font-size: 9px; padding: 3px 8px; border-radius: 4px;
    text-transform: uppercase; letter-spacing: 0.1em;
  }}
  @media print {{ body {{ -webkit-print-color-adjust: exact; }} }}
</style>
</head>
<body>

<!-- HEADER -->
<div class="header">
  <div>
    <div class="brand">Medi<span>Verse</span> AI</div>
    <div class="brand-sub">Intelligent Health Screening Platform</div>
  </div>
  <div class="report-meta">
    <strong>AI Health Report</strong>
    Report ID: {str(report_data.get("id", ""))[:8].upper()}<br/>
    Generated: {created.strftime("%B %d, %Y at %I:%M %p")}<br/>
    Patient: {user_name}
  </div>
</div>

<!-- MODULE BANNER -->
<div class="module-banner">
  <span class="module-icon">{meta["icon"]}</span>
  <div>
    <div class="module-title">{meta["label"]}</div>
    <div class="module-sub">AI Screening Module · MediVerse v2.0</div>
  </div>
</div>

<!-- PATIENT INFO -->
<div class="section">
  <div class="section-title">Patient Information</div>
  <div class="info-grid">
    <div class="info-card">
      <div class="lbl">Patient Name</div>
      <div class="val" style="font-size:14px">{user_name}</div>
    </div>
    <div class="info-card">
      <div class="lbl">Email</div>
      <div class="val" style="font-size:12px">{user_email}</div>
    </div>
    <div class="info-card">
      <div class="lbl">Report Date</div>
      <div class="val" style="font-size:13px">{created.strftime("%d %b %Y")}</div>
    </div>
  </div>
</div>

<!-- CONFIDENCE SUMMARY -->
<div class="section">
  <div class="section-title">Analysis Summary</div>
  <div class="info-grid">
    <div class="info-card">
      <div class="lbl">Module</div>
      <div class="val" style="color:{accent}; font-size:13px">{meta["label"]}</div>
    </div>
    <div class="info-card">
      <div class="lbl">Status</div>
      <div class="val" style="font-size:13px">{report_data.get("status", "completed").title()}</div>
    </div>
    <div class="info-card">
      <div class="lbl">AI Confidence</div>
      <div class="val">{conf_pct}</div>
      <div class="conf-bar-bg"><div class="conf-bar"></div></div>
    </div>
  </div>
</div>

<!-- RESULTS -->
<div class="section">
  <div class="section-title">Detailed Results</div>
  <table class="results">
    <tbody>
      {result_rows}
    </tbody>
  </table>
  {risk_flags_html}
</div>

<!-- DISCLAIMER -->
<div class="section">
  <div class="section-title">Medical Disclaimer</div>
  <div class="disclaimer">
    ⚠️ {disclaimer}
  </div>
</div>

<!-- FOOTER -->
<div class="footer">
  <div>
    MediVerse AI · <em>Powered by ResNet1D, EfficientNet, XGBoost</em>
  </div>
  <div style="display:flex;align-items:center;gap:10px;">
    <span>For clinical review only</span>
    <span class="confidential">Confidential</span>
  </div>
</div>

</body>
</html>"""


# ── PDF generation ────────────────────────────────────────────────────────────

def generate_pdf_bytes(report_data: dict, user_name: str, user_email: str) -> bytes:
    """
    Generate a PDF from a report dict.
    Tries weasyprint first, falls back to fpdf2.
    """
    html = _build_html(report_data, user_name, user_email)

    # Attempt weasyprint
    try:
        from weasyprint import HTML as WP_HTML
        buf = io.BytesIO()
        WP_HTML(string=html).write_pdf(buf)
        buf.seek(0)
        logger.info("PDF generated via weasyprint")
        return buf.read()
    except ImportError:
        logger.info("weasyprint not available, falling back to fpdf2")
    except Exception as e:
        logger.warning("weasyprint failed: %s, falling back to fpdf2", e)

    # fpdf2 fallback (text-only, no HTML rendering)
    try:
        from fpdf import FPDF
        meta = MODULE_META.get(report_data["module_type"], {"label": report_data["module_type"], "color": "#6366f1", "icon": "📋"})
        result = report_data.get("result_json", {})
        created = datetime.fromisoformat(str(report_data.get("created_at", datetime.now().isoformat())))

        pdf = FPDF()
        pdf.set_auto_page_break(True, margin=20)
        pdf.add_page()

        # Title block
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(15, 15, 35)
        pdf.cell(0, 12, "MediVerse AI — Health Report", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 7, meta["label"], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Patient / date
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 6, f"Patient: {user_name} · {user_email}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Date: {created.strftime('%d %B %Y, %I:%M %p')}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Divider
        pdf.set_draw_color(226, 232, 240)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(5)

        # Results
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 15, 35)
        pdf.cell(0, 8, "Analysis Results", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)

        priority_keys = [
            ("rhythm_type", "Rhythm"), ("prediction", "Prediction"),
            ("risk_level", "Risk Level"), ("severity", "Severity"),
            ("recommendation", "Recommendation"), ("risk_flags", "Risk Flags"),
        ]
        for key, label in priority_keys:
            val = result.get(key)
            if val is None:
                continue
            if isinstance(val, list):
                val = ", ".join(str(v) for v in val) or "None"
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(55, 7, f"{label}:", border=0)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 7, str(val))

        pdf.ln(4)
        pdf.set_draw_color(226, 232, 240)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(4)

        # Disclaimer
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 6,
            "DISCLAIMER: This report is generated by MediVerse AI for screening purposes only. "
            "It is NOT a confirmed medical diagnosis. Always consult a qualified healthcare "
            "professional before making any medical decisions."
        )

        buf = io.BytesIO()
        pdf.output(buf)
        buf.seek(0)
        logger.info("PDF generated via fpdf2 fallback")
        return buf.read()

    except ImportError:
        raise RuntimeError(
            "No PDF library found. Install weasyprint: pip install weasyprint\n"
            "or fpdf2: pip install fpdf2"
        )
